const router = require('express').Router();
const controller = require('../controllers/biController');
const { authenticate, requireRoles, requireModule } = require('../middlewares/authMiddleware');
router.use(authenticate);
router.get('/filter-options', requireModule('biExecutive', 'biFinancial', 'biTechnicians', 'biAudit'), controller.filterOptions);
router.get('/executive', requireModule('biExecutive'), controller.executive);
router.get('/technicians', requireModule('biTechnicians'), controller.technicians);
router.get('/audit', requireModule('biAudit'), controller.audit);
router.get('/financial', requireModule('biFinancial'), controller.financial);
module.exports = router;
