const router = require('express').Router();
const controller = require('../controllers/materialRequestController');
const { authenticate, requireRoles, requireModule } = require('../middlewares/authMiddleware');
router.use(authenticate, requireModule('materialRequests'));
router.get('/', controller.list);
router.get('/summary', controller.summary);
router.get('/:id', controller.get);
router.post('/', controller.create);
router.post('/:id/approve', controller.approve);
router.post('/:id/reject', controller.reject);
router.post('/:id/deliver', controller.deliver);
module.exports = router;
