const router = require('express').Router();
const controller = require('../controllers/stockController');
const { authenticate, requireRoles, requireModule } = require('../middlewares/authMiddleware');
router.use(authenticate);
router.get('/overview', requireRoles('admin', 'supervisor', 'estoquista'), requireModule('stock', 'operationsCockpit'), controller.overview);
router.get('/assets', requireRoles('admin', 'supervisor', 'estoquista'), requireModule('patrimony'), controller.assets);
router.get('/serial-life/:serial', requireRoles('admin', 'supervisor', 'estoquista', 'tecnico'), requireModule('serialLife'), controller.serialLife);
router.get('/movements', requireRoles('admin', 'supervisor', 'estoquista'), requireModule('movementHistory'), controller.movements);
router.get('/technician-losses', requireRoles('admin', 'supervisor', 'estoquista'), requireModule('technicianLosses'), controller.losses);
router.get('/technician-box/:id', requireRoles('admin', 'supervisor', 'estoquista'), requireModule('technicianBoxControl', 'technicianInbox'), controller.technicianBox);
router.post('/technician-box/move-to-client', requireRoles('admin', 'supervisor', 'estoquista', 'tecnico'), requireModule('technicianInbox', 'serviceOrders'), controller.moveFromTechnicianToClient);
router.post('/technician-box/loss', requireRoles('admin', 'supervisor', 'estoquista'), requireModule('technicianLosses'), controller.registerTechnicianLoss);
router.post('/technician-box/return-to-stock', requireRoles('admin', 'supervisor', 'estoquista'), requireModule('technicianBoxControl'), controller.returnFromTechnician);
module.exports = router;
