const router = require('express').Router();
const controller = require('../controllers/technicianController');
const { authenticate, requireRoles, requireModule } = require('../middlewares/authMiddleware');
router.use(authenticate);
router.get('/', requireModule('technicians', 'transfers', 'technicianBoxControl', 'technicianLosses', 'technicianReturns', 'lossEvaluation', 'materialRequests'), controller.list);
router.get('/:id', requireModule('technicians', 'technicianBoxControl', 'technicianLosses', 'technicianReturns', 'lossEvaluation', 'transfers'), controller.get);
router.get('/:id/stock', requireModule('technicianInbox', 'technicianBoxControl', 'technicianReturns'), controller.stock);
router.post('/', requireModule('technicians'), controller.create);
router.put('/:id', requireModule('technicians'), controller.update);
module.exports = router;
