const router = require('express').Router();
const controller = require('../controllers/transferController');
const { authenticate, requireRoles } = require('../middlewares/authMiddleware');
router.use(authenticate, requireRoles('admin', 'supervisor'));
router.get('/', controller.list);
router.get('/:id', controller.get);
router.put('/:id', requireRoles('admin'), controller.update);
router.post('/', controller.create);
router.post('/:id/sign', controller.sign);
module.exports = router;
