const router = require('express').Router();
const controller = require('../controllers/transferController');
const { authenticate, requireRoles, requireModule } = require('../middlewares/authMiddleware');
router.use(authenticate, requireModule('transfers'));
router.get('/', controller.list);
router.get('/:id', controller.get);
router.put('/:id', controller.update);
router.post('/', controller.create);
router.post('/:id/sign', controller.sign);
module.exports = router;
