const router = require('express').Router();
const controller = require('../controllers/warehouseController');
const { authenticate, requireRoles, requireModule } = require('../middlewares/authMiddleware');
router.use(authenticate);
router.get('/', requireModule('warehouses', 'receiving', 'transfers', 'materialRequests', 'technicianInbox', 'technicianBoxControl', 'technicianReturns'), controller.list);
router.post('/transfer-stock', requireModule('warehouses', 'transfers'), controller.transferStock);
router.post('/:id/request-delete', requireModule('warehouses'), controller.requestDelete);
router.get('/:id', requireModule('warehouses'), controller.get);
router.post('/', requireModule('warehouses'), controller.create);
router.put('/:id', requireModule('warehouses'), controller.update);
module.exports = router;
